name: CI - build and test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test
      run: ./gradlew build
    - name: Reports
      run: ./gradlew Reports
    - name: deploy reports to site
      run: ./gradlew deployReports
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: project/build/reports
    - name: Deploy reports using an SSH agent
      run: |
        eval $(ssh-agent -s -t 600)
        ssh-add <(echo "${{ secrets.REPORTS_SSH_KEY }}")
        git config --global user.email "kcarr030@odu.edu"
        git config --global user.name "Project Actions"
        ./gradlew deployWebsite